### ISSUE TITLE
rework french/english content storage method

### ISSUE THREAD

**Issue by Phanoix** [gctools-outilsgc/gcconnex#650]
Rework french/english content storage method to not use metadata for storage of full content of blogs, group descriptions, etc.

**Comment by pandurx** [comment]
are we meeting up for this?

**Comment by pandurx** [comment]
@klecuyer the group names are fixed (and here is the ticket)

**Comment by klecuyer** [comment]
language coding still showing up in description of a Group's image:
![image](https://user-images.githubusercontent.com/29754185/29140852-f4b79bba-7d19-11e7-8b52-1c3830bbfdce.png)

**Comment by Steph4104** [comment]
@klecuyer is it still an issue?

**Comment by klecuyer** [comment]
@Steph4104 no :)
